### ISSUE TITLE
Compilation: mpi.h not found

### ISSUE THREAD

**Issue by rainman110** [helmholtz-analytics/mpi4torch#1]
OpenMPI installs its mpi.h under ``/usr/include/mpi/mpi.h`` . The csrc file includes however ``<mpi.h>``.

We should either change the include to ``<mpi/mpi.h>`` or setup.py must figure out the include directory of mpi. I am not sure though, whether the different mpi vendors put the includes into the same prefix or not.

**Comment by d1saster** [comment]
Could you retry? I changed `setup.py` to decativate the ninja build, since that one does not necessarily use `mpicc`.

**Comment by rainman110** [comment]
Works now
